// <copyright file="GlobalSuppressions.cs" company="demian INC.">
// Copyright (c) demian INC. All Rights Reserved.Licensed under the Apache License, Version 2.0.
// See LICENSE in the project root for license information.
// </copyright>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:Element should begin with upper-case letter", Justification = "It is OK in this case", Scope = "member", Target = "~P:DataFactory.Configuration.ClientsDto._id")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "It is OK in this case", Scope = "member", Target = "~P:DataFactory.Configuration.ClientsDto._id")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "It is OK in this case", Scope = "member", Target = "~P:DataFactory.Configuration.ClientsDto.Addresses")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.BrowsersConfiguration")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.DeviceSettings")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "It is OK in this case", Scope = "member", Target = "~M:DataFactory.Configuration.ConfigureConfigurationParameters.Configure(DataFactory.Configuration.ConfigurationParameters)")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Android7")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Android7Capabilities")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Android8")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Ios11")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Android8Capabilities")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Ios11Capabilities")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Ios12")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Ios12Capabilities")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.GeneralParameters")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "It is OK in this case", Scope = "member", Target = "~M:DataFactory.Configuration.Configuration.WrittableConfiguration.#ctor(Microsoft.Extensions.Configuration.IConfiguration,Microsoft.Extensions.DependencyInjection.IServiceCollection)")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.UrlParameters")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "It is OK in this case", Scope = "member", Target = "~M:DataFactory.Configuration.ClientsDtoSerializer.Deserialize(MongoDB.Bson.Serialization.BsonDeserializationContext,MongoDB.Bson.Serialization.BsonDeserializationArgs)~System.Collections.Generic.List{DataFactory.Configuration.ClientAddressDto}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "It is OK in this case", Scope = "member", Target = "~M:DataFactory.Configuration.ClientsDtoSerializer.Serialize(MongoDB.Bson.Serialization.BsonSerializationContext,MongoDB.Bson.Serialization.BsonSerializationArgs,System.Collections.Generic.List{DataFactory.Configuration.ClientAddressDto})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "It is OK in this case", Scope = "member", Target = "~M:DataFactory.Configuration.Configuration.WritableOptions`1.Update(System.Action{`0})")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.DeviceSettings")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.BrowsersConfiguration")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Android7")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Android7Capabilities")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Ios12")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Ios11Capabilities")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Ios12Capabilities")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Ios11")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Android8Capabilities")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.GeneralParameters")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.UrlParameters")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "It is OK in this case", Scope = "type", Target = "~T:DataFactory.Configuration.Android8")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "It is OK in this case", Scope = "member", Target = "~P:DataFactory.Configuration.ClientsDto._id")]
